[toolchain]
# Menentukan versi Solana toolchain (opsional, bisa diatur sesuai kebutuhan)
solana_version = "2.2.0"  # Contoh versi, sesuaikan dengan yang kamu gunakan

[features]
resolution = true
skip-lint = false

[programs.devnet]  # Ubah dari localnet ke devnet
solana_counter = "DGmJsbjsife1p3QoueUruomvJXLaYXMwqEFgE4bV4xrg"

[registry]
url = "https://api.apr.dev" 

[provider]
cluster = "Devnet"  # Ubah dari Localnet ke Devnet
wallet = "~/.config/solana/id.json"  # Lokasi wallet default Solana CLI

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"